// react/src/NodeComponent.jsx
import * as React from 'react';

import { ShapeComponent } from "@jsplumbtoolkit/browser-ui-react"

import anchorPositions from "./anchor-positions"

export default function NodeComponent({ctx}) {

    const { vertex, toolkit } = ctx;
    const data = vertex.data;

    return <div style={{color:data.textColor}} className="flowchart-object" data-jtk-target="true">

        <ShapeComponent ctx={ctx} showLabels={true} labelProperty="text"/>

        {anchorPositions.map(ap => <div className={"jtk-connect jtk-connect-" + ap.id} data-jtk-anchor-x={ap.x} data-jtk-anchor-y={ap.y} data-jtk-orientation-x={ap.ox}  data-jtk-orientation-y={ap.oy} data-jtk-source="true" data-jtk-port-type="source" key={ap.id}></div>)}

        <div className="node-delete node-action delete" onClick={() => toolkit.removeNode(vertex)}></div>
    </div>
}

// svelte/src/lib/NodeComponent.svelte
<script>

    import { anchorPositions } from "../constants"

	import { ShapeComponent } from "@jsplumbtoolkit/browser-ui-svelte"

	export let data;
	export let toolkit;
	export let surface;
	export let vertex;

	function removeNode() {
	    toolkit.removeNode(vertex)
    }

</script>

<div style="color:{data.textColor}" class="flowchart-object" data-jtk-target="true">

    <ShapeComponent surface={surface} vertex={vertex} data={data} showLabels="true" labelProperty="text"/>

    {#each anchorPositions as anchor}
		<div class="jtk-connect jtk-connect-{anchor.id}"
			 data-jtk-anchor-x={anchor.x}
			 data-jtk-anchor-y={anchor.y}
			 data-jtk-orientation-x={anchor.ox}
			 data-jtk-orientation-y={anchor.oy}
			 data-jtk-source="true"></div>
    {/each}

	<div class="node-delete node-action delete" on:click={() => removeNode()}></div>
</div>
